#!/bin/bash
if [[ $(which go) ]]; then
  GOPATH="$HOME/.go"
fi

if [[ $(which wine) ]]; then
  WINEPREFIX="$HOME/.wine"
  WINEARCH="win64"
fi

if [[ $(which vim) ]]; then
  EDITOR="vim"
  VISUAL=$EDITOR
  SUDO_EDITOR=$EDITOR
fi
